name: Deploy Bicep Infra

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy (dev/test/prod)'
        required: true
        default: 'dev'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Bicep
        uses: azure/arm-deploy@v2
        with:
          scope: resourcegroup
          resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP }}
          region: ${{ secrets.AZURE_REGION }}
          template: infra/main.bicep
          parameters: infra/env/${{ github.event.inputs.environment }}.parameters.json
          deploymentName: bicep-${{ github.event.inputs.environment }}
