name: Validate Bicep Templates

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Azure CLI (includes Bicep)
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          az bicep install

      - name: Validate root main.bicep
        run: |
          az bicep build --file infra/main.bicep

      - name: Validate all module files
        run: |
          find infra/modules -name "*.bicep" -print0 | while IFS= read -r -d '' file; do
            echo "Building $file"
            az bicep build --file "$file"
          done
